import type { CatalogEntry, LayoutDelta, Source } from './types.js';

// Mined from Slicer source: Libs/MRML/Core/vtkMRMLLayoutNode.h, enum SlicerLayout.
// Numeric IDs are the SlicerLayout enum values (the int written to
// vtkMRMLLayoutNode::ViewArrangement). Meta values (Initial, Default, None,
// Final, Maximized, Custom, User) are deliberately excluded — those are
// infrastructure, not user-facing options.

const LAYOUT_SOURCE: Source = {
  kind: 'slicer-source',
  path: 'Libs/MRML/Core/vtkMRMLLayoutNode.h',
  symbol: 'vtkMRMLLayoutNode::SlicerLayout',
  note: 'Enum of all built-in view arrangements.',
};

function L(id: number, symbol: string): LayoutDelta {
  return { kind: 'layout', layoutId: id, layoutSymbol: symbol };
}

export const layoutsCatalog: readonly CatalogEntry<LayoutDelta>[] = [
  // ---- 3D-centric ---------------------------------------------------------
  {
    category: 'layout',
    id: 'one-up-3d',
    label: '3D only',
    description: 'Single 3D view, maximum screen real estate for volume rendering and models.',
    delta: L(4, 'SlicerLayoutOneUp3DView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'dual-3d',
    label: 'Dual 3D',
    description: 'Two side-by-side 3D views — useful for comparing rendering parameters or viewpoints.',
    delta: L(15, 'SlicerLayoutDual3DView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'tabbed-3d',
    label: 'Tabbed 3D',
    description: 'Multiple 3D views as tabs in a single viewport.',
    delta: L(9, 'SlicerLayoutTabbed3DView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'triple-3d-endoscopy',
    label: 'Triple 3D (endoscopy)',
    description: 'Three 3D views configured for endoscopic navigation.',
    delta: L(19, 'SlicerLayoutTriple3DEndoscopyView'),
    source: [LAYOUT_SOURCE],
  },

  // ---- Slice-centric ------------------------------------------------------
  {
    category: 'layout',
    id: 'one-up-red',
    label: 'Axial only',
    description: 'Single Red (axial) slice view, full screen.',
    appliesWhen: { hasVolume: true },
    delta: L(6, 'SlicerLayoutOneUpRedSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'one-up-yellow',
    label: 'Sagittal only',
    description: 'Single Yellow (sagittal) slice view, full screen.',
    appliesWhen: { hasVolume: true },
    delta: L(7, 'SlicerLayoutOneUpYellowSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'one-up-green',
    label: 'Coronal only',
    description: 'Single Green (coronal) slice view, full screen.',
    appliesWhen: { hasVolume: true },
    delta: L(8, 'SlicerLayoutOneUpGreenSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'tabbed-slice',
    label: 'Tabbed slices',
    description: 'All slice views collapsed into tabs in a single viewport.',
    appliesWhen: { hasVolume: true },
    delta: L(10, 'SlicerLayoutTabbedSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'side-by-side',
    label: 'Side by side',
    description: 'Two slice views side by side — good for comparing two planes.',
    appliesWhen: { hasVolume: true },
    delta: L(29, 'SlicerLayoutSideBySideView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'three-by-three-slice',
    label: '3×3 slices',
    description: 'Nine slice viewports arranged in a 3×3 grid.',
    appliesWhen: { hasVolume: true },
    delta: L(33, 'SlicerLayoutThreeByThreeSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-by-three-slice',
    label: '4×3 slices',
    description: 'Twelve slice viewports arranged in a 4×3 grid.',
    appliesWhen: { hasVolume: true },
    delta: L(30, 'SlicerLayoutFourByThreeSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-by-two-slice',
    label: '4×2 slices',
    description: 'Eight slice viewports arranged in a 4×2 grid.',
    appliesWhen: { hasVolume: true },
    delta: L(31, 'SlicerLayoutFourByTwoSliceView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'five-by-two-slice',
    label: '5×2 slices',
    description: 'Ten slice viewports arranged in a 5×2 grid.',
    appliesWhen: { hasVolume: true },
    delta: L(32, 'SlicerLayoutFiveByTwoSliceView'),
    source: [LAYOUT_SOURCE],
  },

  // ---- Mixed 3D + slice ---------------------------------------------------
  {
    category: 'layout',
    id: 'conventional',
    label: 'Conventional',
    description: '3D view on top, three slice views below (red/yellow/green).',
    appliesWhen: { hasVolume: true },
    delta: L(2, 'SlicerLayoutConventionalView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'conventional-widescreen',
    label: 'Conventional (widescreen)',
    description: 'Conventional layout optimized for widescreen displays.',
    appliesWhen: { hasVolume: true },
    delta: L(16, 'SlicerLayoutConventionalWidescreenView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-up',
    label: '4-up (3D + axial + sagittal + coronal)',
    description: 'The classic four-quadrant medical view.',
    appliesWhen: { hasVolume: true },
    delta: L(3, 'SlicerLayoutFourUpView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'two-over-two',
    label: '2 over 2',
    description: 'Two views on top, two views on bottom.',
    appliesWhen: { hasVolume: true },
    delta: L(27, 'SlicerLayoutTwoOverTwoView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'three-over-three',
    label: '3 over 3',
    description: 'Three slice views on top, three slice views on bottom.',
    appliesWhen: { hasVolume: true },
    delta: L(21, 'SlicerLayoutThreeOverThreeView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-over-four',
    label: '4 over 4',
    description: 'Four views on top, four views on bottom — eight viewports total.',
    appliesWhen: { hasVolume: true },
    delta: L(22, 'SlicerLayoutFourOverFourView'),
    source: [LAYOUT_SOURCE],
  },

  // ---- Comparison ---------------------------------------------------------
  {
    category: 'layout',
    id: 'compare',
    label: 'Compare (rows)',
    description: 'Multi-row comparison grid — configurable rows of slice views.',
    appliesWhen: { hasVolume: true },
    delta: L(12, 'SlicerLayoutCompareView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'compare-grid',
    label: 'Compare (grid)',
    description: 'Full N×M comparison grid of slice views.',
    appliesWhen: { hasVolume: true },
    delta: L(23, 'SlicerLayoutCompareGridView'),
    source: [LAYOUT_SOURCE],
  },

  // ---- Plot / table -------------------------------------------------------
  {
    category: 'layout',
    id: 'one-up-plot',
    label: 'Plot only',
    description: 'Single plot viewport.',
    appliesWhen: { hasPlot: true },
    delta: L(39, 'SlicerLayoutOneUpPlotView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'conventional-plot',
    label: 'Conventional + plot',
    description: 'Conventional 3D-and-slices layout with a plot panel.',
    appliesWhen: { hasVolume: true, hasPlot: true },
    delta: L(36, 'SlicerLayoutConventionalPlotView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-up-plot',
    label: '4-up + plot',
    description: 'Four-up medical view with a plot panel.',
    appliesWhen: { hasVolume: true, hasPlot: true },
    delta: L(37, 'SlicerLayoutFourUpPlotView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-up-plot-table',
    label: '4-up + plot + table',
    description: 'Four-up medical view with both plot and table panels.',
    appliesWhen: { hasVolume: true, hasPlot: true, hasTable: true },
    delta: L(38, 'SlicerLayoutFourUpPlotTableView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'three-over-three-plot',
    label: '3 over 3 + plot',
    description: 'Three-over-three slice grid with a plot panel.',
    appliesWhen: { hasVolume: true, hasPlot: true },
    delta: L(40, 'SlicerLayoutThreeOverThreePlotView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'four-up-table',
    label: '4-up + table',
    description: 'Four-up medical view with a table panel.',
    appliesWhen: { hasVolume: true, hasTable: true },
    delta: L(34, 'SlicerLayoutFourUpTableView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: '3d-table',
    label: '3D + table',
    description: 'Single 3D view with a table panel.',
    appliesWhen: { hasTable: true },
    delta: L(35, 'SlicerLayout3DTableView'),
    source: [LAYOUT_SOURCE],
  },

  // ---- Workflow-specific --------------------------------------------------
  {
    category: 'layout',
    id: 'dicom-browser',
    label: 'DICOM browser',
    description: 'DICOM browser layout for inspecting series before loading.',
    delta: L(41, 'SlicerLayoutDicomBrowserView'),
    source: [LAYOUT_SOURCE],
  },
  {
    category: 'layout',
    id: 'dual-monitor-four-up',
    label: 'Dual monitor 4-up',
    description: 'Four-up extended across two monitors.',
    appliesWhen: { hasVolume: true },
    delta: L(42, 'SlicerLayoutDualMonitorFourUpView'),
    source: [LAYOUT_SOURCE],
  },
];
