// Minimal NRRD writers: a scalar CT volume and a Slicer segmentation (.seg.nrrd) labelmap,
// both carrying RAS geometry from a row-major 4x4 ijkToRAS so they overlay in Slicer.
function dirs(M: number[]) {
  // column vectors (per-voxel step in RAS) for i,j,k; origin = last column
  const i = [M[0], M[4], M[8]], j = [M[1], M[5], M[9]], k = [M[2], M[6], M[10]], o = [M[3], M[7], M[11]];
  return { i, j, k, o };
}
const v3 = (a: number[]) => `(${a[0]},${a[1]},${a[2]})`;

async function writeRaw(path: string, header: string, bytes: Uint8Array) {
  const head = new TextEncoder().encode(header);
  const out = new Uint8Array(head.length + bytes.length);
  out.set(head, 0); out.set(bytes, head.length);
  await Deno.writeFile(path, out);
}

export async function writeCT(path: string, ct: Int16Array, dims: [number, number, number], M: number[]) {
  const { i, j, k, o } = dirs(M);
  const h = `NRRD0004
type: short
dimension: 3
space: right-anterior-superior
sizes: ${dims[0]} ${dims[1]} ${dims[2]}
space directions: ${v3(i)} ${v3(j)} ${v3(k)}
kinds: domain domain domain
endian: little
encoding: raw
space origin: ${v3(o)}

`;
  await writeRaw(path, h, new Uint8Array(ct.buffer, ct.byteOffset, ct.byteLength));
}

export async function writeSeg(path: string, lab: Uint8Array, dims: [number, number, number], M: number[],
  segs: { value: number; name: string; color: [number, number, number] }[]) {
  const { i, j, k, o } = dirs(M);
  let seghdr = `Segmentation_ContainedRepresentationNames:=Binary labelmap|\nSegmentation_MasterRepresentation:=Binary labelmap\n`;
  segs.forEach((s, n) => {
    seghdr += `Segment${n}_ID:=Segment_${s.value}\n`;
    seghdr += `Segment${n}_Name:=${s.name}\n`;
    seghdr += `Segment${n}_LabelValue:=${s.value}\n`;
    seghdr += `Segment${n}_Layer:=0\n`;
    seghdr += `Segment${n}_NameAutoGenerated:=0\n`;
    seghdr += `Segment${n}_Color:=${s.color[0]} ${s.color[1]} ${s.color[2]}\n`;
    seghdr += `Segment${n}_ColorAutoGenerated:=0\n`;
  });
  const h = `NRRD0004
type: unsigned char
dimension: 3
space: right-anterior-superior
sizes: ${dims[0]} ${dims[1]} ${dims[2]}
space directions: ${v3(i)} ${v3(j)} ${v3(k)}
kinds: domain domain domain
${seghdr}endian: little
encoding: raw
space origin: ${v3(o)}

`;
  await writeRaw(path, h, new Uint8Array(lab.buffer, lab.byteOffset, lab.byteLength));
}
